export const products = [
  {
    _id: 1,
    name: "The Naveah Diamond Ring",
    img:
      "https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/l/LR00055-6__1450266466.jpg",
    by: "Jwels",
    category: "Ring",
    price: 10246,
    weight: "0.84 g",
    metal: "Yellow Gold",
    GST: "3 %",
    size: 7,
    rating: 5,
  },
  {
    _id: 2,
    name: "The Blink Diamond Ring",
    img:
      "https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/l/LR02646-6_513.jpg",
    by: "Jwels",
    category: "Ring",
    price: 29089,
    weight: "2.53 g",
    metal: "Yellow Gold",
    GST: "3 %",
    size: 7.5,
    rating: 4,
  },
  {
    _id: 3,
    name: "The Gold Bracelet",
    img:
      "https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/g/GBL02284277_894.jpg",
    by: "Jwels",
    category: "Bracelet",
    price: 90005,
    weight: "13.25 g",
    metal: "Gold",
    GST: "3 %",
    size: 2.5,
    rating: 4,
  },
  {
    _id: 4,
    name: "The Zrimat Diamond Ring",
    img:
      "https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/g/GR00518-6_624.jpg",
    by: "Jwels",
    category: "Ring",
    price: 30174,
    weight: "3.67 g",
    metal: "Yellow Gold",
    GST: "3 %",
    size: 8,
    rating: 3,
  },
  {
    _id: 5,
    name: "The 3 Gold Flowers Gold Bracelet",
    img:
      "https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/c/CZBR00086-6_630.jpg",
    by: "Jwels",
    category: "Bracelet",
    price: 9958,
    weight: "1.64 g",
    metal: "Yellow Gold",
    GST: "3 %",
    size: 2,
    rating: 3,
  },
  {
    _id: 6,
    name: "The Cloud N Kite Gold Bracelet",
    img:
      "https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/c/CZBR00088-6_726.jpg",
    by: "Jwels",
    category: "Bracelet",
    price: 7367,
    weight: "0.96 g",
    metal: "Yellow Gold",
    GST: "3 %",
    size: "",
    rating: 5,
  },
  {
    _id: 7,
    name: "The Osiane Gold Bracelet",
    img:
      "https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/b/BR00416-1__1093242591.jpg",
    by: "Jwels",
    category: "Bracelet",
    price: 16068,
    weight: "3 g",
    metal: "Yellow Gold",
    GST: "3 %",
    size: "",
    rating: 1,
  },
  {
    _id: 8,
    name: "The Berinhard Gold Ring",
    img:
      "https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/z/ZLR00463-6_316.jpg",
    by: "Jwels",
    category: "Ring",
    price: 13495,
    weight: "1.76 g",
    metal: "Yello Gold",
    GST: "3 %",
    size: 6,
    rating: 2,
  },
  {
    _id: 9,
    name: "Diamond Mangalsutra",
    img:
      "https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/m/MS00032-5_590.jpg",
    by: "Jwels",
    category: "Mangalsutra",
    price: 45330,
    weight: "1.51 g",
    metal: "Yellow Gold",
    GST: "3 %",
    size: "",
    rating: 4,
  },
  {
    _id: 10,
    name: "Diamond Mangalsutra with Chain",
    img:
      "https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/m/MS00568-5_577.jpg",
    by: "Jwels",
    category: "Mangalsutra",
    price: 62422,
    weight: "6.87 g",
    metal: "Yellow Gold",
    GST: "3 %",
    size: "",
    rating: 3,
  },
  {
    _id: 11,
    name: "Diamond Mangalsutra with Chain",
    img:
      "https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/m/MS00566-5_980.jpg",
    by: "Jwels",
    category: "Mangalsutra",
    price: 54925,
    weight: "5.83 g",
    metal: "Yellow Gold",
    GST: "5.83 g",
    size: "",
    rating: 4,
  },
  {
    _id: 12,
    name: "The Yashica Diamond Mangalsutra",
    img:
      "https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/t/TN00040-5.jpg",
    by: "Jwels",
    category: "Mangalsutra",
    price: 74503,
    weight: "3.93 g",
    metal: "Yellow Gold",
    GST: "3 %",
    size: "",
    rating: 4,
  },
];
