import { v4 as uuid } from "uuid";

export const products = [
  {
    id: 1,
    name: "The Naveah Diamond Ring",
    img:
      "https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/l/LR00055-6__1450266466.jpg",
    by: "Jwels",
    category: "Ring",
    price: "₹ 10,246",
    weight: "0.84 g",
    metal: "Yello Gold",
    GST: "3 %",
    size: 7,
    rating: 5,
  },
  {
    id: 2,
    name: "The Blink Diamond Ring",
    img:
      "https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/l/LR02646-6_513.jpg",
    by: "Jwels",
    category: "Ring",
    price: "₹ 29,089",
    weight: "2.53 g",
    metal: "Yellow Gold",
    GST: "3 %",
    size: 7.5,
    rating: 4,
  },
  {
    id: 3,
    name: "The Gold Bracelet",
    img:
      "https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/g/GBL02284277_894.jpg",
    by: "Jwels",
    category: "Bracelet",
    price: "₹ 90,005",
    weight: "13.25 g",
    metal: "Gold",
    GST: "3 %",
    size: 2.5,
    rating: 4,
  },
  {
    id: 4,
    name: "The Zrimat Diamond Ring",
    img:
      "https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/g/GR00518-6_624.jpg",
    by: "Jwels",
    category: "Ring",
    price: "₹ 30,174",
    weight: "3.67 g",
    metal: "Yellow Gold",
    GST: "3 %",
    size: 8,
    rating: 3,
  },
  {
    id: 5,
    name: "The 3 Gold Flowers Gold Bracelet",
    img:
      "https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/c/CZBR00086-6_630.jpg",
    by: "Jwels",
    category: "Bracelet",
    price: "₹ 9,958",
    weight: "1.64 g",
    metal: "Yellow Gold",
    GST: "3 %",
    size: 2,
    rating: 3,
  },
  {
    id: 6,
    name: "The Cloud N Kite Gold Bracelet",
    img:
      "https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/c/CZBR00088-6_726.jpg",
    by: "Jwels",
    category: "Bracelet",
    price: "₹ 7,367",
    weight: "0.96 g",
    metal: "Yellow Gold",
    GST: "3 %",
    size: "",
    rating: 5,
  },
  {
    id: 7,
    name: "The Osiane Gold Bracelet",
    img:
      "https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/b/BR00416-1__1093242591.jpg",
    by: "Jwels",
    category: "Bracelet",
    price: "₹ 16,068",
    weight: "3 g",
    metal: "Yellow Gold",
    GST: "3 %",
    size: "",
    rating: 1,
  },
  {
    id: 8,
    name: "The Berinhard Gold Ring",
    img:
      "https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/z/ZLR00463-6_316.jpg",
    by: "Jwels",
    category: "Ring",
    price: "₹ 13,495",
    weight: "1.76 g",
    metal: "Yello Gold",
    GST: "3 %",
    size: 6,
    rating: 2,
  },
  {
    id: 9,
    name: "The Induprabha Diamond Mangalsutra",
    img:
      "https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/m/MS00032-5_590.jpg",
    by: "Jwels",
    category: "Mangalsutra",
    price: "₹ 45,330",
    weight: "1.51 g",
    metal: "Yellow Gold",
    GST: "3 %",
    size: "",
    rating: 4,
  },
  {
    id: 10,
    name: "The Thanu Diamond Mangalsutra with Chain",
    img:
      "https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/m/MS00568-5_577.jpg",
    by: "Jwels",
    category: "Mangalsutra",
    price: "₹ 62,422",
    weight: "6.87 g",
    metal: "Yellow Gold",
    GST: "3 %",
    size: "",
    rating: 3,
  },
  {
    id: 11,
    name: "The Ragil Diamond Mangalsutra with Chain",
    img:
      "https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/m/MS00566-5_980.jpg",
    by: "Jwels",
    category: "Mangalsutra",
    price: "₹ 54,925",
    weight: "5.83 g",
    metal: "Yellow Gold",
    GST: "5.83 g",
    size: "",
    rating: 4,
  },
  {
    id: 12,
    name: "The Yashica Diamond Mangalsutra",
    img:
      "https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/t/TN00040-5.jpg",
    by: "Jwels",
    category: "Mangalsutra",
    price: "₹ 74,503",
    weight: "3.93 g",
    metal: "Yellow Gold",
    GST: "3 %",
    size: "",
    rating: 4,
  },
];
